server:
  servlet:
    # 项目contextPath
    context-path: /api
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 200
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 2
 
# 日志配置
logging:
  config: classpath:logback-spring.xml
  file: /data/logs/${spring.profiles.active}/${spring.application.name}_${spring.profiles.active}.log
  file.max-size: 50MB
  #当参数定义int简单类型并使用@apiModelPerperty标签时,如果不指名example属性,会导致swagger类型转换错误,信息如下
  #java.lang.NumberFormatException: For input string: ""
  level.io.swagger.models.parameters.AbstractSerializableParameter: error


# Mysql Redis Mongodb
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
datasource:
 #从库数量
  readSize: 1
   # 使用druid数据源
  type: com.zaxxer.hikari.HikariDataSource
  aop:
    scan: execution(* com.zyk..*Service.*(..))
#主库
  write:
    jdbc-url: jdbc:p6spy:mysql://192.168.99.100:3306/admin_framework?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: docker_user
    password: 378541
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    filters: stat
    maxActive: 100
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQueryTimeout: 900000
    validationQuery: SELECT SYSDATE() from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: -1
  read1:
    jdbc-url: jdbc:p6spy:mysql://192.168.99.100:3306/admin_framework?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: docker_user
    password: 378541
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    filters: stat
    maxActive: 100
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQueryTimeout: 900000
    validationQuery: SELECT SYSDATE() from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: -1


# Redis
redis:
  ip: 192.168.99.100
  port: 6379
  pool:
    maxActive: 1024
    maxIdle: 200
    maxWait: 10000
    testOnBorrow: true
    testOnReturn: true
    password: 378541


#--------------------------短信--------------------------

# 以下留给应用配置
# =====================================
ignore:
  url: /api/user/info,/api/user/mobile,/api/user/password,/api/activity/enroll,/api/activity/enrolllist
